### PR TITLE
Issue 10

### LINKED ISSUE #10: AppController
In the module example-app, implement this class that, by delegating to an **IEmployeeController** (if not already available in the example-core project, then you must create it in that project in the subpackage "controller", with appropriate methods as you see fit) implements this method

```
void performAction(String actionCode, String arg, PrintStream out)
```

if the actionCode is "showAll" then it must print on the passed out the string representing all the employees. If it is "showOne" then it must print on the passed out the string representing the employee with the id specified in the arg parameter. If there is no employee or the requested employee can't be found it should print an appropriate message, relying on the fact that in such situations the corresponding method of IEmployeeController would return **null**. If the actionCode is another string, or if an argument for the action code is expected but not specified, then the method must throw an IllegalArgumentException.

All the behavior must be tested with mocking.

### PR DESCRIPTION
**Pull request by Wabri**
Closes #10

### CODE REVIEW

File: exercise-app/src/test/java/org/exercise/app/AppControllerTest.java [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+	@Test
+	public void testShowAllWhenThereAreNoEmployees() {
+		assertShowAll("There are no Employees");
+	}
+
+	@Test
+	public void testShowAllWhenThereIsOneEmployee() {
+		Employee employee = new Employee("1", "name1");
+		allEmployees = allEmployees.concat(employee.toString());
+		assertShowAll(allEmployees);
```
Comment (Wabri) [inline exercise-app/src/test/java/org/exercise/app/AppControllerTest.java]: I do not understand why this test fails

File: exercise-app/src/main/java/org/exercise/app/AppController.java [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+	private IEmployeeController employeeController;
+
+	public AppController(IEmployeeController employeeController) {
+		this.employeeController = employeeController;
+	}
+
+	public void performAction(String actionCode, String arg, PrintStream out) {
+		if (actionCode.equals("showAll")) {
+			String allEmployees = employeeController.getAllEmployees();
+			if (!allEmployees.equals("")) {
```
Comment (Wabri) [inline exercise-app/src/main/java/org/exercise/app/AppController.java]: The problem is here

File: exercise-app/pom.xml [hunk 3]
```diff
@@ -23,5 +23,11 @@
       <artifactId>exercise-core</artifactId>
       <version>${project.version}</version>
     </dependency>
+    <dependency>
```
Comment (LorenzoBettini) [inline exercise-app/pom.xml]: Since this is used also in the other project (-core) it is worthwhile to move this dependency in the parent pom

File: exercise-app/src/main/java/org/exercise/app/AppController.java [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+public class AppController {
+
+	private IEmployeeController employeeController;
+
+	public AppController(IEmployeeController employeeController) {
+		this.employeeController = employeeController;
+	}
+
+	public void performAction(String actionCode, String arg, PrintStream out) throws IllegalArgumentException {
+		if (actionCode.equals("showAll") || actionCode.equals("showOne")) {
```
Comment (LorenzoBettini) [inline exercise-app/src/main/java/org/exercise/app/AppController.java]: Method too long and with too many nested if; refactor in separate methods to make it more readable. Moreover, switch statements could be used (supported for strings since Java 7).

DON'T repeat string literals: make it constants.

File: exercise-app/src/main/java/org/exercise/app/AppController.java [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+			String allEmployees = employeeController.getAllEmployees();
```
Comment (LorenzoBettini) [inline exercise-app/src/main/java/org/exercise/app/AppController.java]: You call getAllEmployees also in the case of a single employee: it's a waste of resources.

File: exercise-app/src/main/java/org/exercise/app/AppController.java [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+			if (!allEmployees.equals("")) {
+				if (actionCode.equals("showAll")) {
+					out.print(allEmployees);
+				} else if (actionCode.equals("showOne")) {
+					String employeeById = employeeController.getEmployeeById(arg);
+					if (employeeById.equals("")) {
+						out.print("There are no Employee with this id");
```
Comment (LorenzoBettini) [inline exercise-app/src/main/java/org/exercise/app/AppController.java]: "There is no Employee..."

File: exercise-app/src/test/java/org/exercise/app/AppControllerTest.java [hunk 7]
```diff
@@ -0,0 +1,88 @@
...
+	private String concatNewEmployee(String id, String name) {
+		return (createNewEmployee(id, name).toString()).concat(System.getProperty("line.separator"));
+	}
+
+	private Employee createNewEmployee(String id, String name) {
+		return new Employee(id, name);
+	}
+
+	private void assertShowWhat(String expected, String showWhat, String arg) {
+		when(employeeController.getAllEmployees()).thenReturn(allEmployees);
```
Comment (LorenzoBettini) [inline exercise-app/src/test/java/org/exercise/app/AppControllerTest.java]: This is always stubbed, while it makes sense only in situations when getAllEmployees() is expected to be called.
This is related to the wrong way with which getAllEmployees is always called (see the comment on the SUT).
You should also verify that getAllEmployees is called ONLY in case of a "showAll".

File: exercise-app/src/test/java/org/exercise/app/AppControllerTest.java [hunk 8]
```diff
@@ -0,0 +1,88 @@
...
+
+import org.junit.Before;
+import org.junit.Test;
+
+import com.examples.attsw.exercise.core.controller.IEmployeeController;
+import com.examples.attsw.exercise.core.model.Employee;
+
+public class AppControllerTest {
+
+	private AppController appController;
```
Comment (LorenzoBettini) [inline exercise-app/src/test/java/org/exercise/app/AppControllerTest.java]: You could use the alternative mechanism to initialize and assign mocks, i.e., InjectMocks and Mock annotations and then initMocks in the setup (see the tutorial)

File: exercise-app/src/test/java/org/exercise/app/AppControllerTest.java [hunk 9]
```diff
@@ -0,0 +1,88 @@
...
+	@Test
+	public void testShowOneWheneEmployeeDoesNotExists() {
+		allEmployees = concatNewEmployee("1", "name1");
+		when(employeeController.getEmployeeById("2")).thenReturn("");
+		assertShowWhat("There are no Employee with this id", "showOne", "2");
+	}
+
+	@Test
+	public void testShowOneWhenEmployeeExists() {
+		Employee employee = createNewEmployee("1", "name1");
```
Comment (LorenzoBettini) [inline exercise-app/src/test/java/org/exercise/app/AppControllerTest.java]: This test should not need to create Employee objects: the App itself is agnostic concerning objects, since it only communicates with the controller.
When you stub the controller you should not need to use Employee objects but just return strings; how the controller returns strings is not this SUT's business.

**Review by LorenzoBettini — CHANGES_REQUESTED** [review]

File: exercise-app/src/test/java/org/exercise/app/AppControllerTest.java (hunk 8 above)
Comment (Wabri) [reply exercise-app/src/test/java/org/exercise/app/AppControllerTest.java]: I know but i think this is more readable then the other mechanism... anyway i'm going to use InjectMocks.

File: exercise-app/src/test/java/org/exercise/app/AppControllerTest.java [hunk 10]
```diff
@@ -0,0 +1,99 @@
...
+		assertShowOne(employee, "1", employee);
+	}
+
+	@Test(expected = IllegalArgumentException.class)
+	public void testOtherStringInActionCodeArgument() {
+		assertShowWhat("", "", "");
+	}
+
+	private String concatNewEmployee(String employee) {
+		return (employee).concat(System.getProperty("line.separator"));
```
Comment (LorenzoBettini) [inline exercise-app/src/test/java/org/exercise/app/AppControllerTest.java]: the parenthesis are useless around employee (Sonarqube would complain about that :)

File: exercise-app/src/test/java/org/exercise/app/AppControllerTest.java [hunk 11]
```diff
@@ -0,0 +1,99 @@
...
+		appController.performAction(show, arg, out);
+		assertEquals(expected, new String(baos.toByteArray(), StandardCharsets.UTF_8));
+	}
+
+	private void assertShowAll(String expected) {
+		when(employeeController.getAllEmployees()).thenReturn(allEmployees);
+		assertShowWhat(expected, "", AppController.SHOW_ALL);
+	}
+
+	private void assertShowOne(String expected, String id, String thenReturn) {
```
Comment (LorenzoBettini) [inline exercise-app/src/test/java/org/exercise/app/AppControllerTest.java]: better to use another name instead of "thenReturn"... e.g., stringToReturn, or something else

File: exercise-core/src/main/java/com/examples/attsw/exercise/core/controller/EmployeeController.java [hunk 12]
```diff
@@ -20,7 +20,7 @@ public String getAllEmployees() {
 	}
 
 	public String getEmployeeById(String id) {
-		return employeeService.getEmployeeById(id).getName();
+		return employeeService.getEmployeeById(id).toString();
```
Comment (LorenzoBettini) [inline exercise-core/src/main/java/com/examples/attsw/exercise/core/controller/EmployeeController.java:23]: for didactic and exercise purposes, it would be nice to open a new issue about this bug in EmployeeController and a separate PR, that only fixes the problem in EmployeeController (and updates the corresponding test).

In this PR you can simply merge with the branch of the other PR even if it's not yet approved (or cherry pick the corresponding commits).

No merge conflicts would arise when both PR are merged.

File: exercise-core/src/test/java/com/examples/attsw/exercise/core/controller/EmployeeControllerTest.java [hunk 13]
```diff
@@ -58,7 +58,7 @@ public void testGetEmployeeByIdWhenEmployeeDoesntExists() {
 	public void testGetEmployeeByIdWhenEmployeeExists() {
 		Employee newEmployee = newEmployee("1", "nameTest");
 		when(employeeService.getEmployeeById("1")).thenReturn(newEmployee);
-		assertEquals(newEmployee.getName(), employeeController.getEmployeeById("1"));
+		assertEquals(newEmployee.toString(), employeeController.getEmployeeById("1"));
```
Comment (LorenzoBettini) [inline exercise-core/src/test/java/com/examples/attsw/exercise/core/controller/EmployeeControllerTest.java:61]: see the comment above on EmployeeController

**Review by LorenzoBettini — CHANGES_REQUESTED** [review]
looks much better now!

See the remaining comments and in particular the one on EmployeeController

File: exercise-core/src/main/java/com/examples/attsw/exercise/core/controller/EmployeeController.java (hunk 12 above)
Comment (Wabri) [reply exercise-core/src/main/java/com/examples/attsw/exercise/core/controller/EmployeeController.java:23]: I opened #23 and correctly solved the bug in a new branch, so i opened a new PR on my fork with a 'Closes #23' comment but it didn't work on merging (maybe i had to open this issue on my fork). However i manually closed the problem.

**Comment by Wabri** [comment]
Need a review

**Comment by LorenzoBettini** [comment]
There are still pending comments to be addressed

**Comment by Wabri** [comment]
I thought i had already solved them, sorry!
